### ISSUE TITLE
Version 1.1.2 readGyroscope & readAcceleration functionality reversed?

### ISSUE THREAD

**Issue by DIvkov575** [arduino-libraries/Arduino_LSM6DSOX#27]
Im new to embedded/Arduino/accelerometers, but im pretty sure the functionality is reversed w/ Gyro returning acceleration & Acceleration returning Gyro data.

Im using V1.1.2 and Arduino Nano rp2040 connect

**Comment by DIvkov575** [comment]
This seems like too large of an overlook, so I am very doubtful that this is an issue with the library.

**Comment by aentinger** [comment]
I've just cross-checked the addresses used for reading gyro/acc data from the IMU and they conform with the datasheet (i.e. **0x22** = `OUTX_L_G `= **Gyro X Axis**). The problem is likely on your end.
