### ISSUE TITLE
[Feature Request] Access embedded temperature sensor

### ISSUE THREAD

**Issue by julienmartin84** [arduino-libraries/Arduino_LSM6DSOX#7]
Hello!

I saw in the Nano RP2040 Connect documentation that the **ST LSM6DSOXTR** has an embedded temperature sensor. The Arduino library does not allow access to its value for the moment. Could it be possible to have access to it?

Thank you!

**Comment by aentinger** [comment]
Hi @julienmartin84 :wave:  Here you've got it (#9) :wink:

**Comment by julienmartin84** [comment]
Thank you. I will test it today!

**Edit**: it's working fine 😉
@aentinger Is the sensor precision limited to integer? Also, do you have an idea of when this change will be available in a new library version?
